### PR TITLE
Converted HaxlSharp.Core and HaxlSharp.Fetcher to PCLs

### PR DESCRIPTION
**Pull request by cstrachan88**
I converted the Core and Fetcher projects to portable class libraries in order to use them in a wider range of projects.

### CODE REVIEW

**Comment by joashc** [comment]
Thanks for this- I'm not familiar with PCLs so this is really helpful! I'm happy to merge this, but I'd be more comfortable if the hashing library was included as a nuget package. This would make verifying the origin of the DLL a bit easier, which can be pretty important when dealing with crypto libraries.

Let me know what you think!

**Comment by cstrachan88** [comment]
I agree 100%. I guess I should have done that before making the pull request. I did try the PCLCrypto nuget package, but their MD5 hash failed when I ran your tests. I have some time this evening so I can take a look.

**Comment by cstrachan88** [comment]
Should be good to go now. I swapped out that library with the [BouncyCastle](https://www.nuget.org/packages/BouncyCastle/) nuget package. All tests passed.

**Comment by joashc** [comment]
Looks good, thanks mate!

**Pull request merged**
